import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import ClientNavbarWrapper from "@/components/ClientNavbarWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DuocLink",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/icondl.png", sizes: "32x32", type: "image/png" },
      { url: "/icondl.png", sizes: "192x192", type: "image/png" },
      { url: "/icondl.png", sizes: "512x512", type: "image/png" },
    ],
    apple: "/icondl.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={`${geistSans.className} ${geistMono.className} antialiased`}>
        <ClientNavbarWrapper />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
